const mongoose=require("mongoose");
const asAdmin=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    AadharNo:{
        type:Number,
        unique:true,
        required:true
    },
    country:{
        type:String,
        required:true
    },
    Address:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    pincode:{
        type:Number,
        required:true
    },
    phonenumber:{
        type:Number,
        unique:true,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    judgeid:{
        type:Number,
        unique:true,
        required:true
    },
},{timestamps:true});
const admins =mongoose.model("admin",asAdmin)
module.exports=admins;